# Default values for nodejs , fastapi, mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  frontend:
    repository: nanakia1031/prj-frontend

  mariadb:
    repository: mariadb:10.6.19-focal

  admin:
    repository: nanakia1031/prj-admin

  visitor:
    repository: nanakia1031/prj-visitor

service:
  frontend:
    port: 3000

  mariadb:
    port: 3306

  admin:
    port: 8000

  visitor:
    port: 8050